# Data Analysis

### Libraries

In [33]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import self
plt.style.use('ggplot')

Reading Data

In [34]:
df_languages = pd.read_csv('../data/languages.csv')
df_movies = pd.read_csv('../data/movies.csv')
df_posters = pd.read_csv('../data/posters.csv')
df_releases = pd.read_csv('../data/releases.csv')
df_studios = pd.read_csv("../data/studios.csv")
df_themes = pd.read_csv("../data/themes.csv")
df_reviews = pd.read_csv('../data/rotten_tomatoes_reviews.csv')
df_oscars = pd.read_csv('../data/the_oscar_awards.csv')
df_actors = pd.read_csv('../data/actors.csv')
df_countries = pd.read_csv('../data/countries.csv')
df_crew = pd.read_csv('../data/crew.csv')
df_genres = pd.read_csv('../data/genres.csv')

Data shapes

In [35]:
print(df_languages.shape)
print(df_movies.shape)
print(df_posters.shape)
print(df_releases.shape)
print(df_studios.shape)
print(df_themes.shape)
print(df_oscars.shape)
print(df_reviews.shape)
print(df_actors.shape)
print(df_countries.shape)
print(df_crew.shape)
print(df_genres.shape)

(1038762, 3)
(941597, 7)
(941597, 2)
(1332782, 5)
(679283, 2)
(125641, 2)
(10889, 7)
(1129887, 9)
(5798450, 3)
(693476, 2)
(4720183, 3)
(1046849, 2)

In [36]:
df_languages.head(5)

        id              type language
0  1000001          Language  English
1  1000002  Primary language   Korean
2  1000002   Spoken language  English
3  1000002   Spoken language   German
4  1000002   Spoken language   Korean

In [37]:
df_movies.head(5)

,id,name,date,tagline,description,minute,rating
0,1000001,Barbie,2023.0,She's everything. He's just Ken.,Barbie and Ken are having the time of their li...,114.0,3.86
1,1000002,Parasite,2019.0,Act like you own the place.,"All unemployed, Ki-taek's family takes peculia...",133.0,4.56
2,1000003,Everything Everywhere All at Once,2022.0,The universe is so much bigger than you realize.,An aging Chinese immigrant is swept up in an i...,140.0,4.30
3,1000004,Fight Club,1999.0,Mischief. Mayhem. Soap.,A ticking-time-bomb insomniac and a slippery s...,139.0,4.27
4,1000005,La La Land,2016.0,Here's to the fools who dream.,"Mia, an aspiring actress, serves lattes to mov...",129.0,4.09

In [38]:
df_posters.head(5)

        id                                               link
0  1000001  https://a.ltrbxd.com/resized/film-poster/2/7/7...
1  1000002  https://a.ltrbxd.com/resized/film-poster/4/2/6...
2  1000003  https://a.ltrbxd.com/resized/film-poster/4/7/4...
3  1000004  https://a.ltrbxd.com/resized/film-poster/5/1/5...
4  1000005  https://a.ltrbxd.com/resized/film-poster/2/4/0...

In [39]:
df_releases.head(5)

        id    country        date        type rating
0  1000001    Andorra  2023-07-21  Theatrical    NaN
1  1000001  Argentina  2023-07-20  Theatrical    ATP
2  1000001  Australia  2023-07-19  Theatrical     PG
3  1000001  Australia  2023-10-01     Digital     PG
4  1000001    Austria  2023-07-20  Theatrical    NaN

In [40]:
df_studios.head(5)

        id                   studio
0  1000001  LuckyChap Entertainment
1  1000001             Heyday Films
2  1000001           NB/GG Pictures
3  1000001                   Mattel
4  1000001    Warner Bros. Pictures

In [41]:
df_themes.head(5)

        id                                              theme
0  1000001                   Humanity and the world around us
1  1000001                             Crude humor and satire
2  1000001                        Moving relationship stories
3  1000001     Emotional and captivating fantasy storytelling
4  1000001  Surreal and thought-provoking visions of life ...

In [42]:
df_reviews.head(5)

,rotten_tomatoes_link,movie_title,critic_name,top_critic,publisher_name,review_type,review_score,review_date,review_content
0,m/0814255,Percy Jackson & the Olympians: The Lightning T...,Andrew L. Urban,False,Urban Cinefile,Fresh,NaN,2010-02-06,A fantasy adventure that fuses Greek mythology...
1,m/0814255,Percy Jackson & the Olympians: The Lightning T...,Louise Keller,False,Urban Cinefile,Fresh,NaN,2010-02-06,"Uma Thurman as Medusa, the gorgon with a coiff..."
2,m/0814255,Percy Jackson & the Olympians: The Lightning T...,NaN,False,FILMINK (Australia),Fresh,NaN,2010-02-09,With a top-notch cast and dazzling special eff...
3,m/0814255,Percy Jackson & the Olympians: The Lightning T...,Ben McEachen,False,Sunday Mail (Australia),Fresh,3.5/5,2010-02-09,Whether audiences will get behind The Lightnin...
4,m/0814255,Percy Jackson & the Olympians: The Lightning T...,Ethan Alter,True,Hollywood Reporter,Rotten,NaN,2010-02-10,What's really lacking in The Lightning Thief i...

In [43]:
df_oscars.head(5)

,year_film,year_ceremony,ceremony,category,name,film,winner
0,1927,1928,1,ACTOR,Richard Barthelmess,The Noose,False
1,1927,1928,1,ACTOR,Emil Jannings,The Last Command,True
2,1927,1928,1,ACTRESS,Louise Dresser,A Ship Comes In,False
3,1927,1928,1,ACTRESS,Janet Gaynor,7th Heaven,True
4,1927,1928,1,ACTRESS,Gloria Swanson,Sadie Thompson,False

In [44]:
df_actors.head(5)

        id               name    role
0  1000001      Margot Robbie  Barbie
1  1000001       Ryan Gosling     Ken
2  1000001    America Ferrera  Gloria
3  1000001  Ariana Greenblatt   Sasha
4  1000001           Issa Rae  Barbie

In [45]:
df_countries.head(5)

        id      country
0  1000001           UK
1  1000001          USA
2  1000002  South Korea
3  1000003          USA
4  1000004      Germany

In [46]:
df_crew.head(5)

        id      role            name
0  1000001  Director    Greta Gerwig
1  1000001  Producer    Tom Ackerley
2  1000001  Producer   Margot Robbie
3  1000001  Producer  Robbie Brenner
4  1000001  Producer    David Heyman

In [47]:
df_genres.head(5)

        id      genre
0  1000001     Comedy
1  1000001  Adventure
2  1000002     Comedy
3  1000002   Thriller
4  1000002      Drama

In [48]:
print("Languages types:\n", df_languages.dtypes, "\n")
print("Movies types:\n",df_movies.dtypes,"\n")
print("Posters types:\n",df_posters.dtypes,"\n")
print("Releases types:\n",df_releases.dtypes,"\n")
print("Studios types:\n", df_studios.dtypes, "\n")
print("Themes types:\n",df_themes.dtypes,"\n")
print("Reviews_types:\n",df_reviews.dtypes,"\n")
print("Oscars types:\n",df_oscars.dtypes,"\n")
print("Actors types:\n",df_actors.dtypes,"\n")
print("Countries types:\n",df_countries.dtypes,"\n")
print("Crew types:\n",df_crew.dtypes,"\n")
print("Genres types:\n",df_genres.dtypes,"\n")

Languages types:
 id           int64
type        object
language    object
dtype: object

Movies types:
 id               int64
name            object
date           float64
tagline         object
description     object
minute         float64
rating         float64
dtype: object

Posters types:
 id       int64
link    object
dtype: object

Releases types:
 id          int64
country    object
date       object
type       object
rating     object
dtype: object

Studios types:
 id         int64
studio    object
dtype: object

Themes types:
 id        int64
theme    object
dtype: object

Reviews_types:
 rotten_tomatoes_link    object
movie_title             object
critic_name             object
top_critic                bool
publisher_name          object
review_type             object
review_score            object
review_date             object
review_content          object
dtype: object

Oscars types:
 year_film         int64
year_ceremony     int64
ceremony          int64
category         object
name             object
film             object
winner             bool
dtype: object

Actors types:
 id       int64
name    object
role    object
dtype: object

Countries types:
 id          int64
country    object
dtype: object

Crew types:
 id       int64
role    object
name    object
dtype: object

Genres types:
 id        int64
genre    object
dtype: object

Converting "actors.csv" columns into types

In [49]:
df_actors["id"] = df_actors["id"].astype('int')
df_actors["name"] = df_actors["name"].astype('string')
df_actors["role"] = df_actors["role"].astype('string')

Converting "countries.csv" columns into types

In [50]:
df_countries["id"] = df_countries["id"].astype('int')
df_countries["country"] = df_countries["country"].astype('string')

Converting "crew.csv" columns into types

In [51]:
df_crew["id"] = df_crew["id"].astype('int')
df_crew["role"] = df_crew["role"].astype('string')
df_crew["name"] = df_crew["name"].astype('string')

Converting "genres.csv" columns into type

In [52]:
df_crew["id"] = df_crew["id"].astype('int')
df_genres["genre"] = df_genres["genre"].astype('string')

Converting "languages.csv" columns into type

In [53]:
df_languages['type'] = df_languages['type'].astype('string')
df_languages['language'] = df_languages['language'].astype('string')

Converting "movies.csv" columns into type

In [54]:
df_movies['name'] = df_movies['name'].astype('string')
df_movies['date'] = pd.to_datetime(df_movies['date'],
errors='coerce', format='%Y').fillna(pd.to_datetime(df_movies['date'],errors='coerce'))
df_movies['tagline'] = df_movies['tagline'].astype('string')
df_movies['description'] = df_movies['description'].astype('string')

Converting "posters.csv" columns into type

In [55]:
df_posters['link'] = df_posters['link'].astype('string')

Converting "releases.csv" columns into type

In [56]:
df_releases['date'] = pd.to_datetime(df_releases['date'],
errors='coerce', format='%Y').fillna(pd.to_datetime(df_releases['date'],errors='coerce'))
df_releases['type'] = df_releases['type'].astype('string')
df_releases['rating'] = df_releases['rating'].astype('string')
df_releases['country'] = df_releases['country'].astype('string')

Converting "studios.csv" column types

In [57]:
df_studios['studio'] = df_studios['studio'].astype('string')

Converting "themes.csv" column types

In [58]:
df_themes['theme'] = df_themes['theme'].astype('string')

Converting "rotten_tomatoes_reviews.csv" column types

In [59]:
df_reviews['rotten_tomatoes_link'] = df_reviews['rotten_tomatoes_link'].astype('string')
df_reviews['movie_title'] = df_reviews['movie_title'].astype('string')
df_reviews['critic_name'] = df_reviews['critic_name'].astype('string')
df_reviews['publisher_name'] = df_reviews['publisher_name'].astype('string')
df_reviews['review_type'] = df_reviews['review_type'].astype('string')
df_reviews['review_score'] = df_reviews['review_score'].astype('string')
df_reviews['review_date'] = pd.to_datetime(df_reviews['review_date'], errors = 'coerce', format = '%Y').fillna(pd.to_datetime(df_reviews['review_date'], errors = 'coerce'))
df_reviews['review_content'] = df_reviews['review_content'].astype('string')

Converting "the_oscar_awards.csv" column types

In [59]:
df_oscars['category'] = df_oscars['category'].astype('string')
df_oscars['name'] = df_oscars['name'].astype('string')
df_oscars['film'] = df_oscars['film'].astype('string')

Checking naN values and duplicates in "languages.csv" dataframe

In [ ]:
print("NaN values in column ID\n",df_languages.loc[df_languages['id'].isna()])
print("\nNaN values in column TYPE\n",df_languages.loc[df_languages['type'].isna()])
print("\nNaN values in column LANGUAGE\n",df_languages.loc[df_languages['language'].isna()])
print("\nDuplicated lines\n",df_languages.loc[df_languages.duplicated()])

Checking naN values and duplicates in "movies.csv" dataframe

In [ ]:
print("NaN values in column ID\n",df_movies.loc[df_movies['id'].isna()])
print("\nNaN values in column NAME\n",df_movies.loc[df_movies['name'].isna()]) 
print("\nNaN values in column DATE\n",df_movies.loc[df_movies['date'].isna()])
print("\nNaN values in column TAGLINE\n",df_movies.loc[df_movies['tagline'].isna()])
print("\nNaN values in column DESCRIPTION\n",df_movies.loc[df_movies['description'].isna()])
print("\nNaN values in column MINUTE\n",df_movies.loc[df_movies['minute'].isna()])
print("\nNaN values in column RATING\n",df_movies.loc[df_movies['rating'].isna()])

print("\nDuplicated lines\n",df_movies.loc[df_movies.duplicated()])

Checking naN values and duplicates in "posters.csv" dataframe

In [ ]:
print("NaN values in column ID\n",df_posters.loc[df_posters['id'].isna()])
print("\nNaN values in column LINK\n",df_posters.loc[df_posters['link'].isna()])

print("\nDuplicated lines\n",df_posters.loc[df_posters.duplicated()])
df_posters = df_posters.drop_duplicates()

Checking naN values and duplicates in "releases.csv" dataframe

In [ ]:
print("NaN values in column ID\n",df_releases.loc[df_releases['id'].isna()])
print("\nNaN values in column COUNTRY\n",df_releases.loc[df_releases['country'].isna()])
print("\nNaN values in column DATE\n",df_releases.loc[df_releases['date'].isna()])
print("\nNaN values in column TYPE\n",df_releases.loc[df_releases['type'].isna()])
print("\nNaN values in column RATING\n",df_releases.loc[df_releases['rating'].isna()])

print("\nDuplicated lines\n",df_releases.loc[df_releases.duplicated()])